---
title: "ESM204_Assignment4"
author: "Alex Brown"
date: "5/29/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(stargazer)
library(wesanderson)

```

```{r}
mc_abatement <- read_csv("HW4Data.csv")
```

##1 

```{r}
MC_A_model <- lm(MC_A ~ Abatement, data = mc_abatement)

summary(MC_A_model)

A_int <- MC_A_model$coefficients[1]
A_slope <- MC_A_model$coefficients[2]

MC_B_model <- lm(MC_B ~ Abatement, data = mc_abatement)

summary(MC_B_model)

B_int <- MC_B_model$coefficients[1]
B_slope <- MC_B_model$coefficients[2]

MC_C_model <- lm(MC_C ~ Abatement, data = mc_abatement)

summary(MC_C_model)

C_int <- MC_C_model$coefficients[1]
C_slope <- MC_C_model$coefficients[2]

MC_D_model <- lm(MC_D ~ Abatement, data = mc_abatement)

summary(MC_D_model)

D_int <- MC_D_model$coefficients[1]
D_slope <- MC_D_model$coefficients[2]

#prod_vis <- ggplot(production_frame, aes(x = year,y = metric_ton, color = prod_by_sector)) +
 # geom_line() +

model_plot <- ggplot(mc_abatement, aes(x = Abatement))+
  geom_point(aes(y = MC_A, color = "MC_A"))+
  geom_smooth(aes(y = MC_A), method = lm, se = FALSE, size = 0.5, color = "red")+
  geom_point(aes(y = MC_B, color = "MC_B"))+
  geom_smooth(aes(y = MC_B), method = lm, se = FALSE, size = 0.5, color = "darkseagreen3")+
  geom_point(aes(y = MC_C, color = "MC_C"))+
  geom_smooth(aes(y = MC_C), method = lm, se = FALSE, size = 0.5, color = "orange")+
  geom_point(aes(y = MC_D, color = "MC_D"))+
  geom_smooth(aes(y = MC_D), method = lm, se = FALSE, size = 0.5, color = "darksalmon")+
  scale_color_manual(values  = wes_palette("Darjeeling1"), name = "Sectors", labels = c("Sector A", "Sector B", "Sector C", "Sector D")) +
  scale_y_continuous(expand = c(0,5)) + # can change back to 0,0 
  scale_x_continuous(expand = c(0,5)) + # can change back to 0,0
  theme_classic() +
  labs(x = "Abatement (tons of CO2)",
       y = "Marginal Cost of Abatement ($/ton)", 
       title = "Marginal Cost") +
  theme(plot.title = element_text(hjust = 0.5))
  

#geom_line(data = catch_df, aes(x = catch_time_seq, y = catch_modeling), color = "red", size = 1)

model_plot
```

##2 
```{r}

sectorAmp = MC_A_model$coefficients[2]*180 + MC_A_model$coefficients[1]
#WTP for first unit is $95.19
sectorBmp = MC_B_model$coefficients[2]*200 + MC_B_model$coefficients[1]
#WTP for first unit is $49.07
sectorCmp = MC_C_model$coefficients[2]*220 + MC_C_model$coefficients[1]
#WTP for first unit is $160.79
sectorDmp = MC_D_model$coefficients[2]*300 + MC_D_model$coefficients[1]
#WTP for first unit is $87.67

#sector C willing to pay the most for the first unit of carbon emissions

# demand function for sector A
q_A <- seq(0,180,by=10)
d_A <- function(q){(A_slope*(180-q)) + A_int}
demand_A <- d_A(q_A)
curve(d_A, from=0, to=300, xlab = "quantity", ylab = "price",  ylim = c(0,200), xlim = c(0,350), col = "red")

# demand function for sector B
q_B <- seq(0,200,by=10)
d_B <- function(q){(B_slope*(200-q) + B_int)}
demand_B <- d_B(q_B)
curve(d_B, from=0, to=300, xlab= "quantity", ylab = "price", add= TRUE,  ylim = c(0,200), xlim = c(0,350), col = "green")

# demand function for sector C
q_C <- seq(0,220,by=10)
d_C <- function(q){(C_slope*(220-q) + C_int)}
demand_C <- d_C(q_C)
curve(d_C, from=0, to=300, xlab= "quantity", ylab = "price", add= TRUE,  ylim = c(0,200), xlim = c(0,350), col = "yellow")

# demand function for sector D
q_D <- seq(0,300,by=10)
d_D <- function(q){(D_slope*(300-q) + D_int)}
demand_D <- d_D(q_D)
curve(d_D, from=0, to=400, xlab= "quantity", ylab = "price", add= TRUE, ylim = c(0,200), xlim = c(0,350), col = "orange")

```